export const state = {
  auth: {
    auth: null,
    authenticated: false,
    token: null,
    tokenSent: false,
    tokenSending: false,
    tokenValid: null,
    tokenValidating: false,
    user: { id: 'anonUser', type: 'Person', name: 'Anonymous' },
  },
  collection: { collection: null, item: null, listItem: null },
  db: { title: 'Default Title' },
  errorMessage: null,
  form: {},
  graph2: {},
  history: {
    activeKey: null,
    firstKey: null,
    key: {},
    lastKey: null,
    refresh: false,
  },
  session: {},
}
